version: 2.1

defaults: &defaults
  docker:
    - image: node:12
  working_directory: ~/snyk-api-import

commands:
  show_node_version:
    description: Log Node and npm version
    steps:
      - run:
          name: Node version
          command: node --version
      - run:
          name: NPM version
          command: npm --version
jobs:
  release:
    <<: *defaults
    docker:
      - image: circleci/node:<< parameters.node_version >>
    resource_class: small
    steps:
      - install_deps
      - run: sudo npm i -g semantic-release @semantic-release/exec pkg
      - run:
          name: Publish to GitHub
          command: semantic-release
    test:
      <<: *defaults
      steps:
        - show_node_version
        - checkout
        - attach_workspace:
            at: ~/snyk-api-import
        - run:
            name: Install
            command: npm i
        - run:
            name: Build
            command: npm run build
        - run:
            name: Run tests
            command: npm test
    lint:
      <<: *defaults
      steps:
        - checkout_and_merge
        - run:
            name: Run linting tasks
            command: npm run lint
workflows:
    version: 2
    nightly:
        triggers:
          - schedule:
              cron: "0 0 * * *"
              filters:
                branches:
                  only:
                    - master
        jobs:
            - build-test-monitor:
                context: SNYK

    test:
      jobs:
        - common:
            name: Common
            context: nodejs-install
            node_version: "12"
            filters:
              branches:
                ignore:
                  - master
        - test:
            name: Tests for Node v12 support
            context: nodejs-install
            node_version: "12"
            requires:
              - Common
            filters:
              branches:
                ignore:
                  - master
        - release:
            name: Release
            context: nodejs-app-release
            node_version: "12"
            filters:
              branches:
                only:
                  - master

                        - release:
          name: Release
          context: nodejs-lib-release
          filters:
            branches:
              only:
                - master
